name: ASTAR

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python: ['3.10']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install -r rq.txt
      - name: Build Cython extension
        run: python setup.py build_ext --inplace
      - name: Upload .so file
        uses: actions/upload-artifact@v2
        with:
          name: astar-files
          path: |
            **/*.so
